# Golden conformance: fixtures generated by edge-analyst/scripts/gen-fixtures.mjs, with expected
# outputs computed by running the reference implementation (src/blocklist.js) itself. A failure
# here means the port drifted from the format owner — fix the port, never the fixture. This is
# the Python twin of camada-core/test/conformance.test.ts, case for case.
from __future__ import annotations

import json
from typing import Any

import pytest

from camada.events.build import HDRS, RequestInfo, build_wire_event
from camada.snapshot.match import Matcher, MatchInput, MatchResult
from camada.snapshot.parse import parse_snapshot

from .conftest import read_bin, read_json

CASES = read_json("blk3/cases.json")
CASES5 = read_json("blk5/cases.json")["v5"]
HDRS_FX = read_json("blk3/hdrs.json")


def matcher(name: str, d: str = "blk3") -> Matcher:
    return Matcher(parse_snapshot(read_bin(f"{d}/{name}.bin"), read_json(f"{d}/{name}.meta.json")))


def as_input(c: dict[str, Any]) -> MatchInput:
    """A v5 case's `headers` is a map with already lower-cased keys — the request as the tap sees
    it. It becomes the header(name) getter §D3 defines, exactly as the reference harness does."""
    i = dict(c["input"])
    headers = i.pop("headers", None)
    return MatchInput(**i, header=(lambda n: headers.get(n)) if headers is not None else None)


def outcome(r: MatchResult) -> dict[str, Any]:
    # the reference reports "nothing matched" as reason null; the port leaves it None too
    return {"block": r.block, "challenge": r.challenge, "allowed": r.allowed, "reason": r.reason}


def outcome5(r: MatchResult) -> dict[str, Any]:
    return {**outcome(r), "warn": r.warn, "action": r.action, "rule": r.rule}


def label(c: dict[str, Any]) -> str:
    return json.dumps(c["input"], separators=(",", ":"))


@pytest.mark.parametrize("version", ["v3", "v4"])
class TestV3V4:
    def test_basic(self, version: str) -> None:
        m = matcher(f"{version}-basic")
        for c in CASES[version]["basic"]:
            assert outcome(m.match(as_input(c))) == c["expect"], label(c)

    def test_empty(self, version: str) -> None:
        m = matcher(f"{version}-empty")
        for c in CASES[version]["empty"]:
            assert outcome(m.match(as_input(c))) == c["expect"], label(c)


class TestV4Outcomes:
    def test_never_two_outcome_flags(self) -> None:
        m = matcher("v4-basic")
        for c in CASES["v4"]["basic"] + CASES["v4"]["empty"]:
            r = m.match(as_input(c))
            assert int(r.allowed) + int(r.block) + int(r.challenge) <= 1

    def test_v3_container_cannot_express_allow_or_challenge(self) -> None:
        v3 = matcher("v3-basic")
        pairs = list(zip(CASES["v4"]["basic"], CASES["v3"]["basic"], strict=True))
        diverged = [(a, b) for a, b in pairs if a["expect"] != b["expect"]]
        assert diverged   # the fixtures must actually exercise the new sections
        for v4c, v3c in diverged:
            assert outcome(v3.match(as_input(v4c))) == v3c["expect"]


class TestV5:
    def test_rules(self) -> None:
        m = matcher("v5-rules", "blk5")
        for c in CASES5["rules"]:
            assert outcome5(m.match(as_input(c))) == c["expect"], label(c)

    def test_empty(self) -> None:
        m = matcher("v5-empty", "blk5")
        for c in CASES5["empty"]:
            assert outcome5(m.match(as_input(c))) == c["expect"], label(c)

    def test_never_two_outcome_flags(self) -> None:
        m = matcher("v5-rules", "blk5")
        for c in CASES5["rules"] + CASES5["empty"]:
            r = m.match(as_input(c))
            assert int(r.allowed) + int(r.block) + int(r.challenge) + int(r.warn) <= 1

    def test_names_the_rule_only_when_a_rule_decided(self) -> None:
        m = matcher("v5-rules", "blk5")
        for c in CASES5["rules"]:
            r = m.match(as_input(c))
            if r.reason == "rule":
                assert r.rule and r.action
            else:
                assert r.rule is None and r.action is None

    def test_rules_overrule_the_sides_a_v4_container_can_only_read(self) -> None:
        v4, rules = matcher("v4-basic"), matcher("v5-rules", "blk5")
        diverged = [c for c in CASES5["rules"] if outcome(v4.match(as_input(c))) != outcome(rules.match(as_input(c)))]
        assert diverged
        for c in diverged:
            assert c["expect"]["reason"] == "rule"

    def test_header_cases_decide_through_the_getter_alone(self) -> None:
        m = matcher("v5-rules", "blk5")
        header_cases = [c for c in CASES5["rules"] if c["input"].get("headers")]
        assert header_cases
        for c in header_cases:
            assert outcome5(m.match(as_input(c))) == c["expect"]
            blind_input = dict(c["input"])
            blind_input.pop("headers")
            blind = m.match(MatchInput(**blind_input))   # no getter: a header condition can never fire (fail open)
            if c["expect"]["reason"] == "rule":
                assert blind.rule != c["expect"]["rule"]
            else:
                assert blind.reason == c["expect"]["reason"]


def test_interleaved_matchers_keep_state_apart() -> None:
    a, b = matcher("v4-basic"), matcher("v4-empty")
    for _ in range(20):
        assert a.match(MatchInput(ip="2001:db8::1")).reason == "ip6"
        assert b.match(MatchInput(ip="2001:db8::1")).block is False
        assert a.match(MatchInput(ip="2001:db8::2")).block is False


class TestHdrsBitmask:
    def test_pins_the_exact_header_order(self) -> None:
        assert list(HDRS) == HDRS_FX["hdrs"]

    def test_hm_vectors(self) -> None:
        for c in HDRS_FX["cases"]:
            ev = build_wire_event(
                RequestInfo(method="GET", host="x.test", path="/", query="", headers=[(n, "v") for n in c["names"]], ip="1.2.3.4"),
                tap="sdk-node", rid="r",
            )
            assert ev["hm"] == c["hm"], "+".join(c["names"])
