#!/usr/bin/env python3
"""Re-vendors @camada/browser's auto build into src/camada/beacon_js.py.

Usage: python scripts/sync_beacon.py [path/to/camada-browser]   (defaults to the sibling checkout)
Run `npm run build` in camada-browser first; tests/test_beacon_js.py fails until the two agree.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[1]
browser = Path(sys.argv[1]) if len(sys.argv) > 1 else root.parent / "camada-browser"
src = (browser / "dist" / "auto.global.js").read_text()
version = json.loads((browser / "package.json").read_text())["version"]
out = root / "src" / "camada" / "beacon_js.py"
out.write_text(
    "# GENERATED by scripts/sync_beacon.py — do not edit. The first-party beacon (@camada/browser's\n"
    "# dist/auto.global.js) vendored as a string: served at /_cam/b.js with no runtime file read.\n"
    "# tests/test_beacon_js.py pins it to the sibling build byte for byte.\n"
    f"BEACON_VERSION = {version!r}\n"
    f"BEACON_SHA256 = {hashlib.sha256(src.encode()).hexdigest()!r}\n"
    f"BEACON_JS = {src!r}\n"
)
print(f"beacon_js.py: @camada/browser/{version}, {len(src)} bytes")
